[[redirects]]
  from = "https://petoux-tp.fr/*"
  to = "https://terrasol83.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.petoux-tp.fr/*"
  to = "https://terrasol83.com/:splat"
  status = 301
  force = true